// <auto-generated />
using System;
using DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBContexts.Migrations
{
    [DbContext(typeof(AthloboostDbContext))]
    partial class AthloboostDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("MuscleGroups")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Carbs")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Fats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Proteins")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Foods", (string)null);
                });

            modelBuilder.Entity("Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoodId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Meals", (string)null);
                });

            modelBuilder.Entity("Models.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Arm")
                        .HasPrecision(2, 5)
                        .HasColumnType("REAL");

                    b.Property<double?>("Calf")
                        .HasPrecision(2, 5)
                        .HasColumnType("REAL");

                    b.Property<double?>("Chest")
                        .HasPrecision(2, 5)
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Forearm")
                        .HasPrecision(2, 5)
                        .HasColumnType("REAL");

                    b.Property<double?>("Neck")
                        .HasPrecision(2, 5)
                        .HasColumnType("REAL");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Waist")
                        .HasPrecision(2, 5)
                        .HasColumnType("REAL");

                    b.Property<double?>("Weight")
                        .HasPrecision(2, 5)
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Measurements", (string)null);
                });

            modelBuilder.Entity("Models.Schedule", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("RestDays")
                        .HasColumnType("varbinary(31)")
                        .HasColumnName("Restdays");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Schedules", (string)null);
                });

            modelBuilder.Entity("Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasPrecision(2, 5)
                        .HasColumnType("REAL");

                    b.Property<int?>("WorkoutExerciseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("Sets", (string)null);
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Facebook")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Followers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Following")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instagram")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("X")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScheduleUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts", (string)null);
                });

            modelBuilder.Entity("Models.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId")
                        .IsUnique();

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises", (string)null);
                });

            modelBuilder.Entity("Models.Exercise", b =>
                {
                    b.HasOne("Models.User", null)
                        .WithMany("Exercises")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Models.Food", b =>
                {
                    b.HasOne("Models.User", null)
                        .WithMany("Foods")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Models.Meal", b =>
                {
                    b.HasOne("Models.Food", "Food")
                        .WithOne()
                        .HasForeignKey("Models.Meal", "FoodId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Models.User", null)
                        .WithMany("Meals")
                        .HasForeignKey("UserId");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Models.Measurement", b =>
                {
                    b.HasOne("Models.User", null)
                        .WithMany("Measurements")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Models.Schedule", b =>
                {
                    b.HasOne("Models.User", null)
                        .WithOne("Schedule")
                        .HasForeignKey("Models.Schedule", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Set", b =>
                {
                    b.HasOne("Models.WorkoutExercise", null)
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId");
                });

            modelBuilder.Entity("Models.Workout", b =>
                {
                    b.HasOne("Models.Schedule", null)
                        .WithMany("Workouts")
                        .HasForeignKey("ScheduleUserId");

                    b.HasOne("Models.User", null)
                        .WithMany("Workouts")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Models.WorkoutExercise", b =>
                {
                    b.HasOne("Models.Exercise", "Exercise")
                        .WithOne()
                        .HasForeignKey("Models.WorkoutExercise", "ExerciseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Models.Workout", null)
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Models.Schedule", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Foods");

                    b.Navigation("Meals");

                    b.Navigation("Measurements");

                    b.Navigation("Schedule");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("Models.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
