export const Languages = {
    en: {
        settings: {
            title: 'Settings',
            account: 'Account',
            preferences: 'Preferences',
            support: 'Support',
            about: 'About',
            editProfile: 'Edit Profile',
            changePassword: 'Change Password',
            privacySettings: 'Privacy Settings',
            language: 'Language',
            darkMode: 'Dark Mode',
            location: 'Location',
            emailNotifications: 'Email Notifications',
            pushNotifications: 'Push Notifications',
            helpCenter: 'Help Center',
            reportBug: 'Report Bug',
            contactUs: 'Contact Us',
            rateApp: 'Rate App',
            termsOfService: 'Terms of Service',
            privacyPolicy: 'Privacy Policy',
            appVersion: 'App Version',
            logout: 'Logout',
            deleteAccount: 'Delete Account',
            confirmLogout: 'Are you sure you want to logout?',
            confirmDelete: 'Are you sure you want to delete your account? This action cannot be undone.',
            cancel: 'Cancel',
            confirm: 'Confirm',
            save: 'Save Changes',
            success: 'Settings updated successfully',
            error: 'Failed to update settings',
            errorLoggingOut: 'Failed to logout. Please try again.',
            errorDeletingAccount: 'Failed to delete account. Please try again.',
            version: 'Version {{version}}',
            emailSupport: 'Contact us at athloboostx@gmail.com',
            darkModeDescription: 'Enable dark mode for better visibility in low light conditions',
            languageDescription: 'Change the app language',
            privacyDescription: 'Manage your privacy settings and data preferences',
            helpDescription: 'Get help and support for using the app',
            reportBugDescription: 'Report any issues or bugs you encounter',
            termsDescription: 'Read our terms of service and user agreement',
            privacyPolicyDescription: 'Learn about how we handle your data',
            logoutDescription: 'Sign out of your account',
            deleteAccountDescription: 'Permanently delete your account and all associated data',
            back: 'Back'
        },
        language: {
            title: 'Language',
            english: 'English',
            bulgarian: 'Bulgarian',
            currentLanguage: 'Current Language'
        },
        privacy: {
            title: 'Privacy Settings',
            profileVisibility: 'Profile Visibility',
            public: 'Public',
            private: 'Private',
            friendsOnly: 'Friends Only',
            dataCollection: 'Data Collection',
            analytics: 'Analytics',
            crashReports: 'Crash Reports',
            marketing: 'Marketing'
        },
        help: {
            title: 'Help Center',
            faq: 'Frequently Asked Questions',
            contact: 'Contact Support',
            report: 'Report a Problem',
            feedback: 'Send Feedback'
        },
        terms: {
            title: 'Terms of Use',
            acceptance: {
                title: '1. Acceptance of Terms',
                content: 'By accessing and using Athloboost, you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the application.'
            },
            service: {
                title: '2. Use of Service',
                content: 'Athloboost is designed to help users track their fitness progress and manage workouts. You agree to use the service only for lawful purposes and in accordance with these Terms.'
            },
            accounts: {
                title: '3. User Accounts',
                content: 'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account.'
            },
            privacy: {
                title: '4. Privacy',
                content: 'Your use of Athloboost is also governed by our Privacy Policy. Please review our Privacy Policy to understand our practices.'
            },
            intellectual: {
                title: '5. Intellectual Property',
                content: 'All content, features, and functionality of Athloboost are owned by us and are protected by international copyright, trademark, and other intellectual property laws.'
            },
            liability: {
                title: '6. Limitation of Liability',
                content: 'Athloboost is provided "as is" without any warranties. We are not liable for any damages arising from your use of the application.'
            },
            changes: {
                title: '7. Changes to Terms',
                content: 'We reserve the right to modify these terms at any time. We will notify users of any material changes via the application or email.'
            },
            contact: {
                title: '8. Contact Information',
                content: 'For any questions about these Terms, please contact us through the Help Center in the application.'
            }
        },
        tabs: {
            home: 'Home',
            explore: 'Explore',
            createPost: 'Create Post',
            nutrition: 'Nutrition',
            profile: 'Profile'
        },
        home: {
            welcome: 'Hello,',
            welcomeBack: 'Welcome back.',
            startWorkout: 'Start your workout, now!',
            todaysWorkout: 'Today\'s Workout',
            trainingPath: 'Training Path',
            exercises: '{{count}} exercises'
        },
        explore: {
            title: 'Explore',
            timeAgo: '{{time}}',
            like: '{{likes}} Likes',
            comment: 'Comment',
            share: 'Share',
            noPosts: 'No posts available',
            search: 'Search posts...',
            restBetweenSets: 'Rest between sets',
            rest: 'rest',
            set: 'Set',
            reps: 'reps',
            upcomingExercises: 'Upcoming Exercises',
            more: 'more',
            completeSet: 'Complete Set'
        },
        createPost: {
            chooseFromGallery: 'Choose from Gallery',
            takePhoto: 'Take Photo',
            writeCaption: 'Write a caption...',
            post: 'Post'
        },
        common: {
            viewAll: 'view all',
            save: 'Save',
            cancel: 'Cancel',
            add: 'Add',
            delete: 'Delete',
            edit: 'Edit',
            done: 'Done',
            error: 'Error',
            success: 'Success',
            schedule: 'Manage Schedule',
            restDays: 'Rest Days',
            reorderWorkouts: 'Reorder Workouts',
            createWorkout: 'Create Workout',
            noWorkoutScheduled: 'No workout scheduled for today',
            
        },
        nutrition: {
            eliteMember: 'Elite Member since',
            stats: 'Nutrition Stats',
            current: 'Current',
            goal: 'Goal',
            kgToGo: '{{kg}} kg to go',
            nutritionPlan: 'Nutrition Plan',
            dailyNutrition: 'Daily Nutrition',
            addFood: 'Add Food',
            chooseMealType: 'Choose a meal type',
            breakfast: 'Breakfast',
            brunch: 'Brunch',
            lunch: 'Lunch',
            dinner: 'Dinner',
            snack: 'Snack',
            foodName: 'Food Name',
            calories: 'Calories',
            weight: 'Weight (kg)',
            goalWeight: 'Goal Weight (kg)',
            waterIntake: 'Water Intake',
            waterUpdateError: 'Failed to update water intake',
            addFoodError: 'Failed to add food',
            deleteFoodError: 'Failed to delete food',
            loadError: 'Failed to load nutrition data',
            toGo: 'to go'
        },
        profile: {
            followers: 'Followers',
            following: 'Following',
            likes: 'Likes',
            follow: 'Follow',
            noPosts: 'No posts available',
            editProfile: 'Edit Profile',
            changePassword: 'Change Password',
            logout: 'Logout',
            deleteAccount: 'Delete Account',
            confirmLogout: 'Are you sure you want to logout?',
            confirmDelete: 'Are you sure you want to delete your account? This action cannot be undone.',
            cancel: 'Cancel',
            confirm: 'Confirm'
        },
        schedule: {
            title: 'Schedule',
            manageSchedule: 'Manage Schedule',
            restDays: 'Rest Days',
            reorderWorkouts: 'Reorder Workouts',
            createWorkout: 'Create Workout',
            noWorkoutScheduled: 'No workout scheduled for today',
            restDay: 'Rest Day',
            restDayDescription: 'Take this time to recover and prepare for your next workout.',
            restDayHydration: 'Stay hydrated throughout the day',
            restDayNutrition: 'Focus on proper nutrition and recovery',
            restDaySleep: 'Get adequate sleep for better recovery',
            updateError: 'Failed to update schedule',
            exercises: 'exercises',
            nextWorkout: 'Next Workout',
            completeWorkout: 'Complete Workout',
            dragToReorder: 'Drag to reorder'
        },
        workout: {
            title: 'Workout',
            startWorkout: 'Start Workout',
            pause: 'Pause',
            resume: 'Resume',
            complete: 'Complete',
            set: 'Set',
            reps: 'Reps',
            rest: 'Rest',
            weight: 'Weight',
            time: 'Time',
            upcomingExercises: 'Upcoming Exercises',
            more: 'more',
            completeSet: 'Complete Set',
            restBetweenSets: 'Rest between sets'
        },
        manageWorkout: {
            title: 'Manage Workout',
            workoutName: 'Workout Name',
            addExercise: 'Add Exercise',
            editExercise: 'Edit Exercise',
            deleteExercise: 'Delete Exercise',
            exerciseName: 'Exercise Name',
            sets: 'Sets',
            reps: 'Reps',
            weight: 'Weight (kg)',
            restTime: 'Rest Time (sec)',
            estimatedTime: 'Estimated Time (min)',
            saveWorkout: 'Save Workout',
            deleteWorkout: 'Delete Workout',
            confirmDelete: 'Are you sure you want to delete this workout?',
            cancel: 'Cancel',
            confirm: 'Confirm'
        },
        feedback: {
            title: 'Feedback',
            sendFeedback: 'Send Feedback',
            feedbackPlaceholder: 'Tell us what you think...',
            submit: 'Submit',
            thankYou: 'Thank you for your feedback!'
        },
        reportBug: {
            title: 'Report Bug',
            describeBug: 'Describe the bug...',
            submit: 'Submit Report',
            thankYou: 'Thank you for your report!'
        },
        editProfile: {
            title: 'Edit Profile',
            username: 'Username',
            email: 'Email',
            bio: 'Bio',
            profilePicture: 'Profile Picture',
            takePhoto: 'Take Photo',
            chooseFromGallery: 'Choose from Gallery',
            removePhoto: 'Remove Photo',
            save: 'Save Changes',
            success: 'Profile updated successfully',
            error: 'Failed to update profile',
            usernameRequired: 'Username is required',
            emailRequired: 'Email is required',
            invalidEmail: 'Invalid email format',
            bioPlaceholder: 'Tell us about yourself...',
            maxBioLength: 'Bio cannot exceed 200 characters'
        },
        changePassword: {
            title: 'Change Password',
            currentPassword: 'Current Password',
            newPassword: 'New Password',
            confirmPassword: 'Confirm New Password',
            save: 'Change Password',
            success: 'Password changed successfully',
            error: 'Failed to change password',
            currentPasswordRequired: 'Current password is required',
            newPasswordRequired: 'New password is required',
            confirmPasswordRequired: 'Please confirm your new password',
            passwordsDontMatch: 'Passwords do not match',
            passwordTooShort: 'Password must be at least 8 characters',
            passwordRequirements: 'Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character'
        },
        login: {
            title: 'Login',
            email: 'Email',
            password: 'Password',
            login: 'Login',
            forgotPassword: 'Forgot Password?',
            noAccount: "Don't have an account?",
            signUp: 'Sign Up',
            emailRequired: 'Email is required',
            passwordRequired: 'Password is required',
            invalidCredentials: 'Invalid email or password',
            error: 'Login failed. Please try again.'
        },
        register: {
            title: 'Create Account',
            username: 'Username',
            email: 'Email',
            password: 'Password',
            confirmPassword: 'Confirm Password',
            register: 'Register',
            haveAccount: 'Already have an account?',
            login: 'Login',
            usernameRequired: 'Username is required',
            emailRequired: 'Email is required',
            passwordRequired: 'Password is required',
            confirmPasswordRequired: 'Please confirm your password',
            passwordsDontMatch: 'Passwords do not match',
            passwordTooShort: 'Password must be at least 8 characters',
            passwordRequirements: 'Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character',
            emailInUse: 'Email is already in use',
            usernameInUse: 'Username is already taken',
            success: 'Account created successfully',
            error: 'Registration failed. Please try again.'
        }
    },
    bg: {
        settings: {
            title: 'Настройки',
            account: 'Акаунт',
            preferences: 'Предпочитания',
            support: 'Поддръжка',
            about: 'За приложението',
            editProfile: 'Редактирай профил',
            changePassword: 'Промени парола',
            privacySettings: 'Настройки за поверителност',
            language: 'Език',
            darkMode: 'Тъмен режим',
            location: 'Локация',
            emailNotifications: 'Имейл известия',
            pushNotifications: 'Push известия',
            helpCenter: 'Помощен център',
            reportBug: 'Докладвай проблем',
            contactUs: 'Свържи се с нас',
            rateApp: 'Оцени приложението',
            termsOfService: 'Условия за ползване',
            privacyPolicy: 'Политика за поверителност',
            appVersion: 'Версия на приложението',
            logout: 'Изход',
            deleteAccount: 'Изтрий акаунт',
            confirmLogout: 'Сигурни ли сте, че искате да излезете?',
            confirmDelete: 'Сигурни ли сте, че искате да изтриете акаунта си? Това действие не може да бъде отменено.',
            cancel: 'Отказ',
            confirm: 'Потвърди',
            save: 'Запази промените',
            success: 'Настройките са обновени успешно',
            error: 'Грешка при обновяване на настройките',
            errorLoggingOut: 'Грешка при изход. Моля, опитайте отново.',
            errorDeletingAccount: 'Грешка при изтриване на акаунта. Моля, опитайте отново.',
            version: 'Версия {{version}}',
            emailSupport: 'Свържете се с нас на athloboostx@gmail.com',
            darkModeDescription: 'Активирайте тъмния режим за по-добра видимост при слаба светлина',
            languageDescription: 'Променете езика на приложението',
            privacyDescription: 'Управлявайте настройките за поверителност и предпочитанията за данни',
            helpDescription: 'Получете помощ и поддръжка за използването на приложението',
            reportBugDescription: 'Докладвайте за проблеми или грешки, които срещнете',
            termsDescription: 'Прочетете нашите условия за ползване и потребителско споразумение',
            privacyPolicyDescription: 'Научете как обработваме вашите данни',
            logoutDescription: 'Излезте от акаунта си',
            deleteAccountDescription: 'Изтрийте завинаги акаунта си и всички свързани данни',
            back: 'Назад'
        },
        language: {
            title: 'Език',
            english: 'Английски',
            bulgarian: 'Български',
            currentLanguage: 'Текущ език'
        },
        privacy: {
            title: 'Настройки за поверителност',
            profileVisibility: 'Видимост на профила',
            public: 'Публичен',
            private: 'Частен',
            friendsOnly: 'Само за приятели',
            dataCollection: 'Събиране на данни',
            analytics: 'Аналитика',
            crashReports: 'Доклади за сривове',
            marketing: 'Маркетинг'
        },
        help: {
            title: 'Помощен център',
            faq: 'Често задавани въпроси',
            contact: 'Свържи се с поддръжката',
            report: 'Докладвай проблем',
            feedback: 'Изпрати обратна връзка'
        },
        terms: {
            title: 'Условия за ползване',
            acceptance: {
                title: '1. Приемане на условията',
                content: 'С достъпването и използването на Athloboost, вие се съгласявате да се подчините на тези Условия за ползване. Ако не сте съгласни с тези условия, моля, не използвайте приложението.'
            },
            service: {
                title: '2. Използване на услугата',
                content: 'Athloboost е създаден да помага на потребителите да следят своя фитнес прогрес и да управляват тренировките си. Вие се съгласявате да използвате услугата само за законни цели и в съответствие с тези Условия.'
            },
            accounts: {
                title: '3. Потребителски акаунти',
                content: 'Вие отговаряте за запазването на поверителността на вашите акаунт данни и за всички действия, които се извършват под вашия акаунт. Трябва да ни уведомите незабавно за всяка неоторизирана употреба на вашия акаунт.'
            },
            privacy: {
                title: '4. Поверителност',
                content: 'Използването на Athloboost се регулира и от нашата Политика за поверителност. Моля, прегледайте нашата Политика за поверителност, за да разберете нашите практики.'
            },
            intellectual: {
                title: '5. Интелектуална собственост',
                content: 'Цялото съдържание, функции и функционалност на Athloboost са наша собственост и са защитени от международни закони за авторско право, търговски марки и други закони за интелектуална собственост.'
            },
            liability: {
                title: '6. Ограничаване на отговорността',
                content: 'Athloboost се предоставя "както е" без никакви гаранции. Ние не носим отговорност за никакви щети, произтичащи от използването на приложението.'
            },
            changes: {
                title: '7. Промени в условията',
                content: 'Запазваме си правото да променяме тези условия по всяко време. Ще уведомим потребителите за всяка съществена промяна чрез приложението или имейл.'
            },
            contact: {
                title: '8. Контактна информация',
                content: 'За всякакви въпроси относно тези Условия, моля, свържете се с нас чрез Помощния център в приложението.'
            }
        },
        tabs: {
            home: 'Начало',
            explore: 'Разгледай',
            createPost: 'Създай публикация',
            nutrition: 'Хранене',
            profile: 'Профил'
        },
        home: {
            welcome: 'Здравей,',
            welcomeBack: 'Добре дошъл отново.',
            startWorkout: 'Започни тренировката си сега!',
            todaysWorkout: 'Днешната тренировка',
            trainingPath: 'Път на тренировката',
            exercises: '{{count}} упражнения'
        },
        explore: {
            title: 'Разгледай',
            timeAgo: '{{time}}',
            like: '{{likes}} Харесвания',
            comment: 'Коментирай',
            share: 'Сподели',
            noPosts: 'Няма налични публикации',
            search: 'Търси публикации...',
            restBetweenSets: 'Почивка между сериите',
            rest: 'почивка',
            set: 'Серия',
            reps: 'повторения',
            upcomingExercises: 'Следващи упражнения',
            more: 'още',
            completeSet: 'Завърши серия'
        },
        createPost: {
            chooseFromGallery: 'Избери от галерията',
            takePhoto: 'Направи снимка',
            writeCaption: 'Напиши описание...',
            post: 'Публикувай'
        },
        common: {
            viewAll: 'виж всички',
            save: 'Запази',
            cancel: 'Отказ',
            add: 'Добави',
            delete: 'Изтрий',
            edit: 'Редактирай',
            done: 'Готово',
            error: 'Грешка',
            success: 'Успех'
        },
        nutrition: {
            eliteMember: 'Elite Member since',
            stats: 'Хранителни Статистики',
            current: 'Текущо',
            goal: 'Цел',
            kgToGo: '{{kg}} kg to go',
            nutritionPlan: 'Хранителен План',
            dailyNutrition: 'Дневна Хранителна Програма',
            addFood: 'Добави Храна',
            chooseMealType: 'Choose a meal type',
            breakfast: 'Закуска',
            brunch: 'Brunch',
            lunch: 'Обяд',
            dinner: 'Вечеря',
            snack: 'Закуска',
            foodName: 'Име на Храната',
            calories: 'Калории',
            weight: 'Weight (kg)',
            goalWeight: 'Goal Weight (kg)',
            waterIntake: 'Прием на Вода',
            waterUpdateError: 'Грешка при обновяване на приема на вода',
            addFoodError: 'Грешка при добавяне на храна',
            deleteFoodError: 'Грешка при изтриване на храна',
            loadError: 'Грешка при зареждане на хранителните данни',
            toGo: 'остава'
        },
        profile: {
            followers: 'Последователи',
            following: 'Следвани',
            likes: 'Харесвания',
            follow: 'Последвай',
            editProfile: 'Редактирай профил',
            changePassword: 'Промени парола',
            logout: 'Изход',
            deleteAccount: 'Изтрий акаунт',
            confirmLogout: 'Сигурни ли сте, че искате да излезете?',
            confirmDelete: 'Сигурни ли сте, че искате да изтриете акаунта си? Това действие не може да бъде отменено.',
            cancel: 'Отказ',
            confirm: 'Потвърди',
            noPosts: 'Няма налични публикации',
        },
        schedule: {
            title: 'Програма',
            manageSchedule: 'Управление на програмата',
            restDays: 'Дни почивка',
            reorderWorkouts: 'Пренареждане на тренировките',
            createWorkout: 'Създай тренировка',
            noWorkoutScheduled: 'Няма планирана тренировка за днес',
            restDay: 'Ден почивка',
            restDayDescription: 'Използвайте това време за възстановяване и подготовка за следващата тренировка.',
            restDayHydration: 'Поддържайте хидратация през целия ден',
            restDayNutrition: 'Фокусирайте се върху правилното хранене и възстановяване',
            restDaySleep: 'Поставете си адекватен сън за по-добро възстановяване',
            updateError: 'Грешка при обновяване на програмата',
            exercises: 'упражнения',
            nextWorkout: 'Следваща тренировка',
            completeWorkout: 'Завърши тренировка'
        },
        workout: {
            title: 'Тренировка',
            startWorkout: 'Започни тренировка',
            pause: 'Пауза',
            resume: 'Продължи',
            complete: 'Завърши',
            set: 'Серия',
            reps: 'Повторения',
            rest: 'Почивка',
            weight: 'Тежест',
            time: 'Време',
            upcomingExercises: 'Следващи упражнения',
            more: 'още',
            completeSet: 'Завърши серия',
            restBetweenSets: 'Почивка между сериите'
        },
        manageWorkout: {
            title: 'Управление на тренировка',
            workoutName: 'Име на тренировката',
            addExercise: 'Добави упражнение',
            editExercise: 'Редактирай упражнение',
            deleteExercise: 'Изтрий упражнение',
            exerciseName: 'Име на упражнението',
            sets: 'Серии',
            reps: 'Повторения',
            weight: 'Тежест (кг)',
            restTime: 'Време за почивка (сек)',
            estimatedTime: 'Приблизително време (мин)',
            saveWorkout: 'Запази тренировка',
            deleteWorkout: 'Изтрий тренировка',
            confirmDelete: 'Сигурни ли сте, че искате да изтриете тази тренировка?',
            cancel: 'Отказ',
            confirm: 'Потвърди'
        },
        feedback: {
            title: 'Обратна връзка',
            sendFeedback: 'Изпрати обратна връзка',
            feedbackPlaceholder: 'Кажете ни какво мислите...',
            submit: 'Изпрати',
            thankYou: 'Благодарим за обратната връзка!'
        },
        reportBug: {
            title: 'Докладвай проблем',
            describeBug: 'Опишете проблема...',
            submit: 'Изпрати доклад',
            thankYou: 'Благодарим за доклада!'
        },
        editProfile: {
            title: 'Редактирай профил',
            username: 'Потребителско име',
            email: 'Имейл',
            bio: 'Биография',
            profilePicture: 'Профилна снимка',
            takePhoto: 'Направи снимка',
            chooseFromGallery: 'Избери от галерията',
            removePhoto: 'Премахни снимката',
            save: 'Запази промените',
            success: 'Профилът е обновен успешно',
            error: 'Грешка при обновяване на профила',
            usernameRequired: 'Потребителското име е задължително',
            emailRequired: 'Имейлът е задължителен',
            invalidEmail: 'Невалиден формат на имейла',
            bioPlaceholder: 'Разкажете ни за себе си...',
            maxBioLength: 'Биографията не може да надвишава 200 символа'
        },
        changePassword: {
            title: 'Промени парола',
            currentPassword: 'Текуща парола',
            newPassword: 'Нова парола',
            confirmPassword: 'Потвърди нова парола',
            save: 'Промени парола',
            success: 'Паролата е променена успешно',
            error: 'Грешка при промяна на паролата',
            currentPasswordRequired: 'Текущата парола е задължителна',
            newPasswordRequired: 'Новата парола е задължителна',
            confirmPasswordRequired: 'Моля, потвърдете новата парола',
            passwordsDontMatch: 'Паролите не съвпадат',
            passwordTooShort: 'Паролата трябва да бъде поне 8 символа',
            passwordRequirements: 'Паролата трябва да съдържа поне една главна буква, една малка буква, една цифра и един специален символ'
        },
        login: {
            title: 'Вход',
            email: 'Имейл',
            password: 'Парола',
            login: 'Влез',
            forgotPassword: 'Забравена парола?',
            noAccount: 'Нямате акаунт?',
            signUp: 'Регистрация',
            emailRequired: 'Имейлът е задължителен',
            passwordRequired: 'Паролата е задължителна',
            invalidCredentials: 'Невалиден имейл или парола',
            error: 'Входът се провали. Моля, опитайте отново.'
        },
        register: {
            title: 'Създай акаунт',
            username: 'Потребителско име',
            email: 'Имейл',
            password: 'Парола',
            confirmPassword: 'Потвърди парола',
            register: 'Регистрация',
            haveAccount: 'Вече имате акаунт?',
            login: 'Влез',
            usernameRequired: 'Потребителското име е задължително',
            emailRequired: 'Имейлът е задължителен',
            passwordRequired: 'Паролата е задължителна',
            confirmPasswordRequired: 'Моля, потвърдете паролата',
            passwordsDontMatch: 'Паролите не съвпадат',
            passwordTooShort: 'Паролата трябва да бъде поне 8 символа',
            passwordRequirements: 'Паролата трябва да съдържа поне една главна буква, една малка буква, една цифра и един специален символ',
            emailInUse: 'Имейлът вече се използва',
            usernameInUse: 'Потребителското име вече е заето',
            success: 'Акаунтът е създаден успешно',
            error: 'Регистрацията се провали. Моля, опитайте отново.'
        }
    }
}; 
